config/routes.rb
MusicApp::Application.routes.draw do

  resources :users do
    resources :interests,  only: [:create, :create_with_songkick, :index, :destroy], controller: "users/interests" do
      post 'create_with_songkick', :on => :collection
    end
  end

  resources :sessions,     only: [:new, :create, :destroy]
  resources :interests,    only: [:index]
  resources :bookmarklets, only: [:new, :show]
  resource  :tracker,      only: [:new], controller: "tracker"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  get "pages/home"
  get "pages/contact"

  root to: 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    redirect_to current_user if signed_in?
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<div class="well drop-shadow">
	<h1>About Us</h1>
	<div class="row">
		<p class="span9">
			Qusic helps you track the songs that you like. 
		</p>
	</div>
	<div class="row">
		<p class="span9">
		You know the routine: you've just discovered an incredible new track by an awesome Brooklyn-based wonderband. They're the next big thing, definitely. You've had their YouTube on repeat...it's had about 400 listens & at least 10 of them are you.
		</p>
	</div>
	<div class="row">
		<p class="span9">
		It's so fresh it doesn't even have a video, so there's no way it's on iTunes or Spotify. It won't even be out for another 3 months...how are you going to keep track of it? 
		</p>
	</div>
	<div class="row">
		<p class="span9">
		Simple.
		</p>
	</div>
	<div class="row">
		<p class="span9">
		Just log onto Qusic, tell us what track it is & we'll email you a link when it's out.  It's as easy as that!
		</p>
	</div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="well drop-shadow">
	<h1>Contact</h1>
	<p>
	  If you'd like to hear more, get involved, or give feedback please email nigel.purves@gmail.com
	</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="well drop-shadow">
<h1>Help</h1>
	<p>
		If you'd like help with Qusic please email nigel.purves@gmail.com.
	</p>
</div>

app/views/static_pages/home.html.erb
<div class="center hero-unit drop-shadow">
  <h1>Welcome to Qusic</h1>
  <h2>
    Keeping track of your favourite tracks!
  </h2>
	<div class="row-fluid welcome-icons">
		<div class="span6 center headphones">
			<%= image_tag('headphones_2.svg') %>
		</div>
		<div class="span6 center">
			<%= image_tag('mail.svg') %>
		</div>
	</div>
	<div class="row-fluid welcome-explain">
		<div class="span6 center">
			<h3>Tell us what you want to track</h3>
		</div>
		<div class="span6 center">
			<h3>We'll email when it comes out</h3>
		</div>
	</div>
	<div class="row-fluid">
		<div>
			<%= link_to "Get started!", signup_path,
                            	class: "btn btn-large btn-primary" %>
		</div>
		<div class="landingpagesmalltext">
			<p>
				or 
				<%= link_to "Sign in", signin_path %>
			</p>
		</div>
	</div>
</div>