config/routes.rb
MusicApp::Application.routes.draw do

  resources :users do
    resources :interests,  only: [:create, :create_with_songkick, :index, :destroy], controller: "users/interests" do
      post 'create_with_songkick', :on => :collection
    end
  end

  resources :sessions,     only: [:new, :create, :destroy]
  resources :interests,    only: [:index]
  resources :bookmarklets, only: [:new, :show]
  resource  :tracker,      only: [:new], controller: "tracker"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  get "pages/home"
  get "pages/contact"

  root to: 'static_pages#home'

end

app/views/shared/_bookmarklet_link.html.erb
<a href="javascript:(function(d){var%20s=d.createElement('script'),h=d.head||d.getElementsByTagName('head')[0];s.id='qusic-script';s.setAttribute('data-qusic-token','<%= user.bookmarklet_token %>');s.src='http://<%= request.host_with_port %>/assets/qusic.js<%= Rails.env.production? ? "'" : "?t='+ (new Date()).getTime()"%>;h.appendChild(s);})(document);" class="btn js-disable">Track it with QUSIC!</a>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_how_do_I_track_a_song.html.erb
Tell us the name of a song you like & we'll send you a link when it comes out.
<br />
Enter the artist & track name on the left & click 'Track this!'.  You can also use our bookmarklet to easily track songs from YouTube, see the top of the page for more.

app/views/shared/_how_do_I_track_an_artist.html.erb
Tell us which artists you like & we'll tell you when they release new stuff.
<br />
Enter each artist name below & click 'Track this!'.  If you're a Songkick user, you can import all your favourite artists in one go on the right-hand side.

app/views/shared/_how_does_the_bookmarklet_work.html.erb
You can track songs from Youtube automatically using your bookmarklet.
<br/>
It sits on your toolbar. When you're watching a video on Youtube click the bookmarklet. It finds the artist & song name automatically. Just click the 'Track this!' button & it's added to your Qusic tracked songs. It's as simple as that! Click above to get started.

app/views/shared/_track_form.html.erb
<%= form_for [:user, @interest_params], :url => { :action => "create", :user_id => @user.to_param }  do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_field :artist_name,	placeholder: "Which artist should we track...?", class: "ui-autocomplete-input" %>
  <%= f.text_field :track_name,		placeholder: "Which song should we track...?" %>
</div>
  <%= f.submit "Track this!", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<div class="well drop-shadow">
  <section class="userinfo">
    <a href="<%= user_path(@user) %>">
      <%= gravatar_for @user, size: 52 %>
    </a>

    <h1><%= @user.name %></h1>
    <span>
      <%= link_to "view my profile", @user %>
    </span>
    <span>
      <% if current_user? @user %>
        <% if @user.has_bookmarklet_token? then %>
          Your bookmarklet:
          <%= render "shared/bookmarklet_link", :user => @user %>
        <% else %>
          Create a bookmarklet!
          <%= link_to "Do it! Now!", new_bookmarklet_path %>
          <span class="howbookmarkletworks">
          <%= link_to 'How does the bookmarklet work?', '#', rel: "popover", :"data-title" => "How does the bookmarklet work?", :"data-content" => render(:partial => 'shared/how_does_the_bookmarklet_work'), class: "popoverhiw" %>
          </span>
        <% end %>
      <% end %>
    </span>
  </section>
</div>