config/routes.rb
MusicApp::Application.routes.draw do

  resources :users do
    resources :interests,  only: [:create, :create_with_songkick, :index, :destroy], controller: "users/interests" do
      post 'create_with_songkick', :on => :collection
    end
  end

  resources :sessions,     only: [:new, :create, :destroy]
  resources :interests,    only: [:index]
  resources :bookmarklets, only: [:new, :show]
  resource  :tracker,      only: [:new], controller: "tracker"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  get "pages/home"
  get "pages/contact"

  root to: 'static_pages#home'

end

app/models/interest.rb
class Interest < ActiveRecord::Base
  require 'songkickr'

  belongs_to :user
  belongs_to :artist
  belongs_to :track

  attr_accessible :source, :url

  validates :user, presence: true

  default_scope order: 'interests.created_at DESC'
  scope :reverse_order, order('created_at ASC')

  def self.build_track_interest(track_name, artist_name)
    track_record = Track.joins(:artist).where('lower("tracks"."name") = ? AND lower("artists"."name") = ?', track_name.downcase, artist_name.downcase).first
    if track_record.nil?
      artist_record = Artist.first(:conditions => ['lower("artists"."name") = ?', artist_name.downcase])
      if artist_record.nil?
        artist_record = Artist.create(name: artist_name)
      end
      track_record = Track.new(name: track_name, artist: artist_record)
      track_record.lookup_links
      track_record.save
    end
    TrackInterest.new(track: track_record)
  end

  def self.build_artist_interest(artist_name)
    artist_record = Artist.first(:conditions => ['lower("artists"."name") = ?', artist_name.downcase])
    if artist_record.nil?
      artist_record = Artist.create(name: artist_name)
    end
    ArtistInterest.new(artist: artist_record)
  end

  def self.build_interest(track_name, artist_name)
    if track_name.nil? || track_name.empty?
      self.build_artist_interest(artist_name)
    else
      self.build_track_interest(track_name, artist_name)
    end
  end

end# == Schema Information
#
# Table name: interests
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  track_id   :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  source     :string(255)
#  url        :string(255)
#

app/models/user.rb
class User < ActiveRecord::Base
  require 'songkickr'

  attr_accessible :email, :name, :password, :password_confirmation, :skusername
  has_secure_password

  attr_accessor :validate_password

  has_many :interests, dependent: :destroy
  has_many :tracks, through: :interests
  has_many :artists, through: :interests     # CHANGED THIS TO THROUGH: :INTERESTS FROM THROUGH: :TRACKS - WILL THAT WORK?!?!?

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }, if: :password_required?
  validates :password_confirmation, presence: true, if: :password_required?


  def has_bookmarklet_token?
    self.bookmarklet_token.present?
  end

  def update_bookmarklet_token!
    create_bookmarklet_token
    self.save!(:validate => false)
  end

  def password_required?
    @validate_password
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    def create_bookmarklet_token
      self.bookmarklet_token = SecureRandom.urlsafe_base64
    end


end
# == Schema Information
#
# Table name: users
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  email             :string(255)
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  password_digest   :string(255)
#  remember_token    :string(255)
#  admin             :boolean         default(FALSE)
#  bookmarklet_token :string(255)
#

app/controllers/users/interests_controller.rb
class Users::InterestsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :index, :destroy]
  before_filter :load_index_data, only: [:index]
  before_filter :correct_user, only: :destroy

  def create
    @interest_params = InterestParams.new(params[:interest_params])

    if @interest_params.valid?
      @interest      = @interest_params.build_interest
      @interest.user = current_user

      if @interest.save
        flash[:success] = "Tracked!"
        redirect_to user_interests_path(current_user)
        return
      end
    end

    load_index_data
    render 'index'
  end

  def create_with_songkick
    if current_user.skusername.nil? || current_user.skusername.empty?
      redirect_to edit_user_path(current_user)
    else

      begin
        importer = SongkickImporter.new(current_user.skusername)
        interests = importer.insert_tracked_artists_for_user(current_user)
        flash[:success] = "Got #{interests.size} artists from the SongKick user #{current_user.skusername}"
      rescue ResourceNotFound
        flash[:error] = "Sorry, unknown SongKick user #{current_user.skusername}"
      rescue APIError
        Rails.logger.error(APIError)
        flash[:error] = "ZOMG! There was a weird error with the SongKick API. Please try again later."
      end

      redirect_to user_interests_path(current_user)
    end
  end

  def index
    @interest_params = InterestParams.new
  end

  def destroy
    @interest.destroy
    redirect_to user_interests_path(current_user)
  end

  private

  def correct_user
    @interest = current_user.interests.find_by_id(params[:id])
    redirect_to user_interests_path(current_user) if @interest.nil?
  end

  def load_index_data
    @user      = User.find(params[:user_id])
    @track_interests = @user.interests.where(:type => "TrackInterest").paginate(page: params[:page])
    @artist_interests = @user.interests.where(:type => "ArtistInterest")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user,  only: [:index, :edit, :update, :destroy]
  before_filter :correct_user,    only: [:edit, :update]
  before_filter :admin_user,      only: :destroy

  def show
    @user = User.find(params[:id])
    load_interest_data
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Qusic!"
      redirect_to user_interests_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def update
    parms = params[:user]

    unless parms[:password].nil? || parms[:password].empty?
      @user.validate_password= true
    end

    if @user.update_attributes(parms)
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to user_interests_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    sign_out
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to root_path
  end



  private

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      not_found unless (@user.id == current_user.id)
    end

    def admin_user
      not_found unless current_user.admin?
    end

    def load_interest_data
      @track_interests = @user.interests.where(:type => "TrackInterest").paginate(page: params[:page])
      @artist_interests = @user.interests.where(:type => "ArtistInterest")
    end
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/interests/_artist_interest.html.erb
<tr>
  <td class="name"><%= artist_interest.name.titlecase %></td>
	<td class="coolnessranking">
    <% if artist_interest.is_last_interest? %>
      You're the <%= artist_interest.position.ordinalize %> tracker of this artist!
    <% else %>
      You were the <%= artist_interest.position.ordinalize %>
      of <%= artist_interest.artist.artist_interests.count %> trackers!
    <% end %>
  </td>
  <td class="actions">
    <% if current_user?(artist_interest.user) %>
      <%= link_to "delete", user_interest_path(artist_interest.user, artist_interest), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </td>
</tr>

app/views/users/interests/_artist_table.html.erb
<div class="artistinterests well drop-shadow">
  <h3>Artists (<%= @user.interests.where(type: ArtistInterest).count %>)</h3>
  <br/>
  <table class="table artistintereststable">
    <tr><%= render :partial => 'users/interests/artist_interest', :collection => @artist_interests, :as => :artist_interest %></tr>
  </table>
  <% if @user == current_user %>
    <% if @user.skusername.nil? || @user.skusername.empty? %>
      <div class="pre_skusername">
        <span>
          To track artists from
        </span>
        <span class="inline">
          <%= image_tag('NP_SK_com_pink_small_v1.png') %>
        </span>
        <%= link_to "tell us your Songkick username", edit_user_path(current_user) %>
      </div>
    <% else %>
      <div>
        <div class="inline pull-left skbutton">
          <%= button_to "Track artists from", create_with_songkick_user_interests_path(@user.to_param), :method => :post, :class => "btn btn-large" %>
        </div>
          <span class="inline sklogo">
            <%= image_tag('NP_SK_com_pink_small_v1.png') %>
          </span>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/interests/_track_interest.html.erb
<tr>
  <td><%= track_interest.artist_name.titlecase %></td>
  <td><%= track_interest.name.titlecase %></td>
  <td><%= time_ago_in_words(track_interest.created_at) %></td>
  <td class="track">
    <span class="itunes">
      <% if track_interest.itunes_link.present? && track_interest.spotify_link.present? %>
        Available on <%= itunes_link(track_interest) %> & <%= spotify_link(track_interest) %>.
      <% elsif track_interest.itunes_link.present? %>
        Available on <%= itunes_link(track_interest) %> & tracked on Spotify.
      <% elsif track_interest.spotify_link.present? %>
        Available on <%= spotify_link(track_interest) %> & tracked on iTunes.
      <% else %>
        We'll tell you as soon as it's out!
      <% end %>
    </span>
  </td>
  <td>
    <% if track_interest.is_last_interest? %>
      You're the <%= track_interest.position.ordinalize %> tracker of this song!
    <% else %>
      You were the <%= track_interest.position.ordinalize %>
      of <%= track_interest.track.track_interests.count %> trackers!
    <% end %>
  </td>
  <td>
    <% if current_user?(track_interest.user) %>
      <%= link_to "delete", user_interest_path(track_interest.user, track_interest), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </td>
</tr>

app/views/users/interests/_track_table.html.erb
<div class="trackinterests well drop-shadow">
  <h3>Songs (<%= @user.tracks.count %>)</h3>
  <% if @user.tracks.any? %>
    <table class="table trackintereststable">
      <tr>
        <td class="track">
          <h3>Artist</h3>
        </td>
        <td class="track">
          <h3>Track</h3>
        </td>
        <td class="miropost">
          <h3>Posted</h3>
        </td>
        <td class="miropost">
          <h3>Availability</h3>
        </td>
        <td class="miropost">
          <h3>Who else is tracking this?</h3>
        </td>
      </tr>
      <tr>
        <%= render :partial => 'users/interests/track_interest', :collection => @track_interests, :as => :track_interest %>
      </tr>
    </table>
    <%= will_paginate @track_interests %>
  <% end %>
</div>

app/views/users/interests/index.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span5">
      <%= render 'shared/user_info' %>
  </aside>
</div>
<div class="row">
  <div class="span12 ">
    <div class="well drop-shadow">
      <h1 class="whatdoesitdo">Qusic tracks the music you love & tells you when it's released</h1>
      <br/>
      <h2 class="togetstarted">To get started go to 'Track something here'</h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="span4">
    <div class="well drop-shadow track_form">
      <h2 class="trackformtitle">Track something here</h2>
      <p>
        <%= link_to 'How do I track an artist?', '#', rel: "popover", :"data-title" => "How do I track an artist?", :"data-content" => render(:partial => 'shared/how_do_I_track_an_artist'), class: "popoverhiw" %>
        <br/>
        <%= link_to 'How do I track a song?', '#', rel: "popover", :"data-title" => "How do I track a song?", :"data-content" => render(:partial => 'shared/how_do_I_track_a_song'), class: "popoverhiw" %>
      </p>
      <%= render 'shared/track_form' %>
    </div>
  </div>
  <div class="span8">
    <%= render 'artist_table' %>
  </div>
</div>
<div class="row">
  <div class="span12">
    <%=  render 'track_table' %>
  </div>
</div>