config/routes.rb
MusicApp::Application.routes.draw do

  resources :users do
    resources :interests,  only: [:create, :create_with_songkick, :index, :destroy], controller: "users/interests" do
      post 'create_with_songkick', :on => :collection
    end
  end

  resources :sessions,     only: [:new, :create, :destroy]
  resources :interests,    only: [:index]
  resources :bookmarklets, only: [:new, :show]
  resource  :tracker,      only: [:new], controller: "tracker"

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  get "pages/home"
  get "pages/contact"

  root to: 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Qusic
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   	about_path %></li>
      <li><%= link_to "Contact", 	contact_path %></li>
			<li><%= link_to "Help",	help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Qusic", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
					<% if signed_in? %>
          <li><%= link_to "Track something", user_interests_path(current_user) %></li>
					<% else %>
					<li><%= link_to "Home", root_path %></li>
					<% end %>
          <% if signed_in? %>
            <li><%= link_to "Other trackers", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#fat-menu" class="dropdown-toggle" data-toggle="dropdown">
                Me <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <!-- TradeDoubler site verification 2131375 -->
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</div>
<%= javascript_include_tag "application" %>
</body>
</html>